
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Include:
    - "spec/**/*"
  Exclude:
    - "lib/**/*"
    - "bin/**/*"
    - "db/schema.rb"

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
